config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :installs

  namespace:signed do
    resources :posts,except:[:show,:new,:edit]
    resources :friends, only: [:index] do     collection do
        get "friend"
      end
    end
  end  
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :user_friends

  def my_friends
  	self.user_friends.collect(&:friend_id)
  end

  def friends
  	UserFriend.where(friend_id: self.id).collect(&:user_id)
  end

  def all_friends
  	friends + my_friends
  end
end

app/models/user_friend.rb
class UserFriend < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/signed/base_controller.rb
class Signed::BaseController < ApplicationController
	before_filter :authenticate_user!
 end

app/controllers/signed/friends_controller.rb
class Signed::FriendsController < Signed::BaseController

	def index
		@friends = User.all
		@all_friends = current_user.all_friends
	end

	def friend
		current_user.user_friends.create(friend_id: params[:friend_id])
	end
end

app/controllers/signed/posts_controller.rb
class Signed::PostsController < Signed::BaseController
	def index
		@posts = Post.all
		@post = Post.new	
	end
	def create
		@new_post = current_user.posts.create(post_params)
        @post = Post.new
    end
    def post_params
        params.require(:post).permit(:content)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signed/base_helper.rb
module Signed::BaseHelper
end

app/helpers/signed/friends_helper.rb
module Signed::FriendsHelper
end

app/helpers/signed/posts_helper.rb
module Signed::PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/signed/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> this is base</title>
  <center><h1><font color="red"> This is Social Networking site</font></h1></center>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">	
				left pannel
			</div>
			<div class="col-sm-9">   
			    <%=yield%>
			</div>	
		</div>

	</div>

</body>
</html>

app/views/signed/friends/friend.js.erb
$("#friend_btn_" + <%= params[:friend_id] %>).html('Friends now!');

app/views/signed/friends/index.html.erb
<table class="table table-bordered">
	<thead>
		<tr>
	      <th> Email </th>
	      <th> Status </th>
	  </tr>
	</thead>
	<tbody>
		<% @friends.each do |friend| %>
		  <tr> 
		  	<td><%= friend.email %></td>
		  	<td> <% if @all_friends.include? friend.id %> 
		  		   <span class="text-info">"You are friends"</span>
		  		 <% else %>
		  		   <span id="friend_btn_<%= friend.id %>"><%= link_to "Friend", friend_signed_friends_path(friend_id: friend.id), remote: true,class: "btn btn-sm btn-success" %></span>
		  		 <% end %>
		  	</td>
		  </tr>
		<% end %>
    </tbody>
</table>

app/views/signed/posts/_form.html.erb
<div class="row well">
    <%= form_for @post, url: signed_posts_path, remote: true do |f| %>
	<%= f.text_area :content %><br>
	<%= f.submit %>
	<br>
	<% end %>
</div>

app/views/signed/posts/_post_content.html.erb
<div class="well">
	<div class="pull-right" >
		<%= post.created_at %>
	</div>
	<div class="row">
		<%= post.user.email %>:
		<%= post.content %>
	</div>
</div>

app/views/signed/posts/create.js.erb
$("#new_posts").prepend("<%= escape_javascript(render('post_content', post: @new_post)) %> ");
$("#post_form").html("<%= escape_javascript(render('form')) %> ")

app/views/signed/posts/index.html.erb
	<div id="post_form">
    	<%= render "form" %>
    </div>
    <div id="new_posts"></div>
	<% @posts.each do |post| %>
	<%= render 'post_content', post: post %>
	<%end%>